name: React CI/CD Pipeline (Local)

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

     
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

  
      - name: Install dependencies
        run: npm ci

      
      - name: Run tests
        run: npm run test -- --watchAll=false

   
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=project \
            -Dsonar.sources=src \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=$SONAR_TOKEN

      - name: Build Docker image
        run: docker build -t muqeem112/project:latest .

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push muqeem112/project:latest

   
      - name: Run container locally
        run: |
          docker-compose up -d
